apiVersion: apps/v1
kind: Deployment
metadata:
  name: memcached
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      name: memcached
  template:
    metadata:
      labels:
        name: memcached
    spec:
      initContainers:
      - name: fetch-source
        image: weaveworks/scope:master-189789ec
        imagePullPolicy: IfNotPresent
        command:
        - curl
        - -o
        - /demosource/demo.json
        - https://raw.githubusercontent.com/weaveworks/scope/v1.13.1/docker/demo.json
      containers:
        - name: memcached
          image: memcached:1.5.11-alpine
          imagePullPolicy: IfNotPresent
          args:
            - -m 16 # Maximum memory to use, in megabytes. 64MB is default. Update memory request below if you change this
            - -p 11211 # Default port, but being explicit is nice.
            - -v # Don't be too verbose, but print warnings.
            - -I 4m # Maximum item size
          ports:
            - name: clients
              containerPort: 11211
          resources:
            requests:
              cpu: 10m # Based on observed values during April 2020
              memory: 18Mi # -m argument + 10% (see memcached documentation for rationale)
        - name: exporter
          image: prom/memcached-exporter:v0.4.1
          args:
            - --memcached.address=localhost:11211
            - --web.listen-address=0.0.0.0:9150
          ports:
            - name: prom
              containerPort: 9150
